### ISSUE TITLE
Prueba de Weka STPM

### ISSUE THREAD

**Issue by morenodelhoyo** [morenodelhoyo/tsemanticas#10]
- [x] Verificar artículo de Vania Bogorny et al.

**Comment by bbaruque** [comment]
http://onlinelibrary.wiley.com/doi/10.1111/j.1467-9671.2011.01246.x/pdf
https://github.com/yipeng/WEKA-STPM

**Comment by morenodelhoyo** [comment]
Weka STPM parece no servirnos de la mejor forma posible. Se estudiará si los algoritmos usados para limpiar las rutas son factibles para ser implementados en nuestra biblioteca.
