### ISSUE TITLE
Herramienta de Data Cleaning

### ISSUE THREAD

**Issue by bbaruque** [morenodelhoyo/tsemanticas#11]
- [x] Comprobar si existe alguna herramienta en Java para realizar esto de forma automática.
- [x] Pensar algortimo(s) a implementar

**Comment by bbaruque** [comment]
Hemos encontrado una herramienta que puede ser interesante (no la hemos probado aún):
https://www.gpsbabel.org/download.html

**Comment by morenodelhoyo** [comment]
El algoritmo implementado será descrito en la documentación del Trabajo de Fin de Máster.
