### ISSUE TITLE
Lectura artículos sobre T.Semanticas

### ISSUE THREAD

**Issue by bbaruque** [morenodelhoyo/tsemanticas#4]
Finalización de la lectura del material facilitado

**Comment by morenodelhoyo** [comment]
Artículos leídos:
- [x] A Survey of Location Prediction Using Trajectory Mining (B.A. Sabarish, R. Karthi and T. Gireeshkumar)
- [x] Semantic trajectory-based high utility item recommendation system (Jia-Ching Ying et al.)
- [x] Semantic Trajectories Modeling and Analysis (Christine Parent et al.)
