### ISSUE TITLE
Osmosis

### ISSUE THREAD

**Issue by morenodelhoyo** [morenodelhoyo/tsemanticas#8]
- [x] Se comprobará la herramienta Osmosis para la carga de mapas osm y datos gpx en PostGIS
- [x] En caso de que funcione, se incluirá un pequeño manual en la documentación (de momento en el wiki)

**Comment by bbaruque** [comment]
Faltaría añadir una estimación a esta tarea (aunque sea tentativa).

**Comment by morenodelhoyo** [comment]
Manual escrito en la documentación
